"""Acceptance checks for SPEC_01 Step 3, the gravity and rotation tools.

Checks 1 to 4 are the ones the specification lists. Check 5 is beyond it and exercises the
SPEC_00 section 7 rule that an unknown key in a control file is an error, which this step is
the first to implement.
"""

import math
import shutil
import sys
from pathlib import Path

import netCDF4
import numpy as np

from casspian.lib import io as cio
from casspian.lib.schema import CasspianSchemaError
from casspian.tools.gravity import build_gravity
from casspian.lib.control import ControlFileError

HERE = Path("reports/step3")
OUT = HERE / "products"
OUT.mkdir(parents=True, exist_ok=True)
REPO = Path("occul_data/lindal")

results = []


def record(number, description, passed, detail):
    results.append((number, description, passed, detail))
    print(f"[{'PASS' if passed else 'FAIL'}] {number}. {description}")
    for line in str(detail).splitlines():
        print(f"        {line}")


# ---------------------------------------------------------------------------
# 1. lindal_gravity.nc, the Null 1981 set
# ---------------------------------------------------------------------------
g = cio.read(REPO / "lindal_gravity.nc", "gravity")
degree = g["degree"].values.tolist()
jv = g["J"].values
status = g["J_status"].values.tolist()
r_norm = float(g["normalization_radius_m"])
gm = float(g["GM_m3s2"])

expected_j = [16479e-6, -937e-6, 84e-6]
ok = (
    degree == [2, 4, 6]
    and all(a == b for a, b in zip(jv.tolist(), expected_j))
    and status == [0, 0, 1]
    and r_norm == 6.0e7
    and gm == 3.7929085e16
)
meanings = g["J_status"].attrs["flag_meanings"].split()
record(1, "lindal_gravity.nc carries the Null 1981 set as specified", ok,
       f"degree = {degree}\n"
       f"J      = {jv.tolist()} (expected {expected_j}, exact equality "
       f"{all(a == b for a, b in zip(jv.tolist(), expected_j))})\n"
       f"J_status = {status} -> {[meanings[s] for s in status]}\n"
       f"normalization_radius_m = {r_norm!r}\n"
       f"GM_m3s2 = {gm!r}\n"
       f"harmonic_convention = {g.attrs['harmonic_convention']!r}\n"
       f"GM_scope = {g.attrs['GM_scope']!r}; GM_system_m3s2 = "
       f"{float(g.attrs['GM_system_m3s2'])!r} (attribute, not a variable)")
g.close()

# ---------------------------------------------------------------------------
# 2. A second run pointed at iess2019
# ---------------------------------------------------------------------------
control = OUT / "iess2019_build.toml"
control.write_bytes(
    (
        "# Generated by the Step 3 acceptance check. Not part of the repository record.\n"
        "[gravity]\n"
        'source = "'
        + str(Path("data_static/harmonics/iess2019.toml").resolve()).replace("\\", "/")
        + '"\n'
        'output = "'
        + str((OUT / "iess2019_gravity.nc").resolve()).replace("\\", "/")
        + '"\n'
        'prefix = "iess2019"\n'
        # SPEC_01 v0.26 and v0.28: every build-file section declares its role; G and R their epoch.
        'role = "reduction"\n'
        'epoch = "2026-09-10"\n'
    ).encode("utf-8")
)
build_gravity.build(control, "gravity")
i = cio.read(OUT / "iess2019_gravity.nc", "gravity")
i_degree = i["degree"].values.tolist()
i_rnorm = float(i["normalization_radius_m"])
record(2, "a second run pointed at iess2019 gives six degrees to 12 and R = 6.033e7",
       i_degree == [2, 4, 6, 8, 10, 12] and i_rnorm == 6.033e7,
       f"degree = {i_degree} ({len(i_degree)} degrees)\n"
       f"J      = {i['J'].values.tolist()}\n"
       f"normalization_radius_m = {i_rnorm!r}\n"
       f"J_status = {i['J_status'].values.tolist()} (all fitted)\n"
       f"uncertainty_scaling = {i.attrs.get('uncertainty_scaling')!r}\n"
       f"GM_m3s2 = {float(i['GM_m3s2'])!r}")
i.close()

# ---------------------------------------------------------------------------
# 3. lindal_rotation.nc
# ---------------------------------------------------------------------------
r = cio.read(REPO / "lindal_rotation.nc", "rotation")
period = float(r["period_s"])
omega = float(r["angular_rate_rad_s"])
exact = 2.0 * math.pi / 38362.4
record(3, "lindal_rotation.nc gives period_s = 38362.4 and 2 pi / period to double precision",
       period == 38362.4 and omega == exact,
       f"period_s = {period!r}\n"
       f"angular_rate_rad_s = {omega!r}\n"
       f"2 pi / 38362.4     = {exact!r}\n"
       f"bit identical = {omega == exact}\n"
       f"transcribed value in the static file = "
       f"{r.attrs.get('angular_rate_transcribed_rad_s')!r}, which differs from the computed "
       f"rate by {abs(omega - float(r.attrs['angular_rate_transcribed_rad_s'])):.3e} rad/s\n"
       f"system_name = {r.attrs['system_name']!r}")
r.close()

# ---------------------------------------------------------------------------
# 4. The reader refuses a G file whose harmonic_convention is a code it does not know
# ---------------------------------------------------------------------------
tampered = OUT / "tampered_gravity.nc"
shutil.copy(REPO / "lindal_gravity.nc", tampered)
with netCDF4.Dataset(tampered, "a") as handle:
    handle.setncattr("harmonic_convention", "CASSPIAN-J2")
try:
    cio.read(tampered, "gravity")
    record(4, "a G file carrying an unknown convention code is refused", False, "not refused")
except CasspianSchemaError as exc:
    record(4, "a G file carrying an unknown convention code is refused", True, str(exc))

# ---------------------------------------------------------------------------
# 5. Beyond the specification: an unknown control file key is an error (SPEC_00 section 7)
# ---------------------------------------------------------------------------
bad = OUT / "unknown_key_build.toml"
bad.write_bytes(
    (
        "[gravity]\n"
        'source = "../../data_static/harmonics/null1981.toml"\n'
        'output = "x.nc"\n'
        'prefix = "x"\n'
        "normalization_radius_m = 6.0e7\n"
    ).encode("utf-8")
)
try:
    build_gravity.build(bad, "gravity")
    record(5, "an unknown key in a control file is an error, not a warning", False, "accepted")
except ControlFileError as exc:
    record(5, "an unknown key in a control file is an error, not a warning", True, str(exc))

print()
failed = [x for x in results if not x[2]]
print(f"{len(results) - len(failed)} of {len(results)} checks pass")
sys.exit(1 if failed else 0)
